version: "2"
services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pix
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
      - 3307:3307
    networks:
      - kafka_network
    restart: on-failure
    volumes:
      - /var/lib/mysql/data:/var/lib/mysql/data
      - /var/lib/mysql/logs:/var/lib/mysql/logs
      - /var/docker/mariadb/conf:/etc/mysql

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_network
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka_network
    depends_on:
      - zookeeper


  pix-produtor:
    depends_on:
      - mariadb
    build: ./aula-01/pix-produtor
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
    environment:

      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mariadb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    networks:
      - kafka_network
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  pix-consumidor:
    depends_on:
      - mariadb
    build:  ./aula-01/pix-consumidor
    restart: on-failure
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mariadb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    networks:
      - kafka_network
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mysql_log:
    driver: local

networks:
  kafka_network:
    driver: bridge

